name: Backend API Tests

on:
  push:
    branches: [main]
    paths:
      - "users-api/**"
  pull_request:
    branches: [main]
    paths:
      - "users-api/**"

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./users-api

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: users-api/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Generate test coverage
        run: npm run test:coverage
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          directory: ./users-api/coverage/
          flags: backend
          name: backend-coverage
