name: Backend API Tests

on:
  push:
    branches: [main]
    paths:
      - "users-api/**"
  pull_request:
    branches: [main]
    paths:
      - "users-api/**"

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./users-api

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
          cache-dependency-path: users-api/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npx jest --maxWorkers=2
      - name: Generate test coverage
        run: npx jest --coverage --maxWorkers=2
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          directory: ./users-api/coverage/
          flags: backend
          name: backend-coverage
